// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['backbone', 'msgbus'], function(Backbone, msgbus) {
  var API, CURRENTUSERDATA, UserModel, currentUser;
  UserModel = (function(_super) {
    __extends(UserModel, _super);

    function UserModel() {
      return UserModel.__super__.constructor.apply(this, arguments);
    }

    UserModel.prototype.name = 'user';

    UserModel.prototype.idAttribute = 'ID';

    return UserModel;

  })(Backbone.Model);
  currentUser = new UserModel;
  CURRENTUSERDATA = CURRENTUSERDATA || {};
  currentUser.set(CURRENTUSERDATA);
  API = {
    getCurrentUser: function() {
      return currentUser;
    }
  };
  msgbus.reqres.setHandler("get:current:user:model", function() {
    return API.getCurrentUser();
  });
  return UserModel;
});
