// Generated by CoffeeScript 1.7.1
define(['marionette', 'msgbus'], function(Marionette, msgbus) {
  window.App = new Marionette.Application;
  App.addRegions({
    headerRegion: '#header-region',
    leftNavRegion: '#left-nav-region',
    mainContentRegion: '#main-content-region',
    breadcrumbRegion: '#breadcrumb-region',
    footerRegion: '#footer-region',
    dialogRegion: '#dialog-region',
    loginRegion: '#login-region'
  });
  App.rootRoute = "";
  msgbus.reqres.setHandler("default:region", function() {
    return App.mainContentRegion;
  });
  msgbus.commands.setHandler("register:instance", function(instance, id) {
    return App.register(instance, id);
  });
  msgbus.commands.setHandler("unregister:instance", function(instance, id) {
    return App.unregister(instance, id);
  });
  App.on("initialize:after", function(options) {
    App.startHistory();
    if (!App.getCurrentRoute()) {
      return App.navigate(this.rootRoute, {
        trigger: true
      });
    }
  });
  return App;
});
