// Generated by CoffeeScript 1.7.1
define(['jquery', 'jquery-validate', 'bootstrap'], function() {
  return $(document).ready(function() {
    var formatLoginData;
    jQuery.validator.setDefaults({
      debug: true,
      success: "valid"
    });
    $('#login-form').validate({
      focusInvalid: false,
      rules: {
        user_name: {
          required: true,
          email: true
        },
        user_password: {
          required: true
        }
      },
      errorPlacement: function(label, element) {
        var parent;
        $('<span class="error"></span>').insertAfter(element).append(label);
        parent = $(element).parent('.input-with-icon');
        return parent.removeClass('success-control').addClass('error-control');
      },
      success: function(label, element) {
        var parent;
        parent = $(element).parent('.input-with-icon');
        return parent.removeClass('error-control').addClass('success-control');
      }
    });
    $('#btn-login').click(function() {
      if ($('#login-form').valid()) {
        return $('#login-form').submit(function() {
          var formAction, loginDetails, loginDetailsArray;
          loginDetailsArray = $(this).serializeArray();
          loginDetails = formatLoginData(loginDetailsArray);
          formAction = {
            'action': 'user-login'
          };
          $.extend(loginDetails, formAction);
          return $.post(AJAXURL, loginDetails, function(response) {});
        });
      } else {
        $('#display-login-msg').empty();
        return $('#display-login-msg').append("<p>not valid form</p>");
      }
    });
    return formatLoginData = function(serializedDataArray) {
      var data;
      data = {};
      $.each(serializedDataArray, function(key, ele) {
        return data[ele.name] = ele.value;
      });
      return data;
    };
  });
});

//# sourceMappingURL=login.map
