// Generated by CoffeeScript 1.7.1
require(["modules/sign-up"], function(SignUp) {
  return describe("Sign up Form", function() {
    return it("serailize data must be proper", function() {
      var values;
      values = [
        {
          name: "key",
          value: "val"
        }
      ];
      return expect(SignUp.getFromData(values)).toBe({
        "key": "val"
      });
    });
  });
});

//# sourceMappingURL=singup.spec.map
