// Generated by CoffeeScript 1.7.1
define("plugins-loader", ['underscore', 'jquery', 'backbone', 'marionette', 'backbonesyphon', 'jqueryvalidate'], function() {});

define("config-loader", ['configs/backbone.config', 'configs/marionette.config', 'configs/jquery.config'], function() {});

define("apps-loader", ['apps/leftnav/leftnav-app', 'apps/header/header-app', 'apps/upload/upload-controller', 'apps/user-profile/user-profile-controller', 'apps/user-domains/show/user-domains-show-controller']);

define("entitites-loader", ['entities/user', 'entities/domains']);

define("app", ['pages/dashboard.app'], function(App) {
  return App;
});

require(['plugins-loader', 'config-loader', 'app', 'entitites-loader', 'apps-loader'], function(p, c, App) {
  return App.start();
});
