// Generated by CoffeeScript 1.7.1
<<<<<<< HEAD
define(['marionette'], function(Marionette) {
  window.App = new Marionette.Application;
  App.addRegions({
    headerRegion: '#header-region',
    leftNavRegion: '#left-nav-region',
    mainContentRegion: '#main-content-region',
    breadcrumbRegion: '#breadcrumb-region',
    footerRegion: '#footer-region',
    dialogRegion: '#dialog-region',
    loginRegion: '#login-region'
  });
  App.rootRoute = "dashboard";
  App.on('start', function() {
    return console.log("Application Started...");
  });
  App.reqres.setHandler("default:region", function() {
    return App.mainContentRegion;
  });
  App.commands.setHandler("when:fetched", function(entities, callback) {
    var xhrs;
    xhrs = _.chain([entities]).flatten().pluck("_fetch").value();
    return $.when.apply($, xhrs).done(function() {
      return callback();
    });
  });
  App.commands.setHandler("register:instance", function(instance, id) {
    return App.register(instance, id);
  });
  App.commands.setHandler("unregister:instance", function(instance, id) {
    return App.unregister(instance, id);
  });
  App.on("initialize:after", function(options) {
    App.startHistory();
    if (!App.getCurrentRoute()) {
      return App.navigate(this.rootRoute, {
        trigger: true
      });
    }
  });
=======
define("plugins-loader", ['underscore', 'jquery', 'backbone', 'marionette', 'backbonesyphon', 'jqueryvalidate'], function() {});

define("config-loader", ['configs/backbone.config', 'configs/marionette.config', 'configs/jquery.config'], function() {});

define("apps-loader", ['apps/leftnav/leftnav-app', 'apps/header/header-app', 'apps/upload/upload-controller', 'apps/user-profile/user-profile-controller', 'apps/user-domains/show/user-domains-show-controller']);

define("entitites-loader", ['entities/user']);

define("app", ['pages/dashboard.app'], function(App) {
>>>>>>> 6888129e2109d9ed9ad8b860bce95e11f998974a
  return App;
});

require(['plugins-loader', 'config-loader', 'app', 'entitites-loader', 'apps-loader'], function(p, c, App) {
  return App.start();
});
