// Generated by CoffeeScript 1.7.1
define(['entities/user', 'msgbus'], function(User, msgbus) {
  return describe("User Entity", function() {
    it("must be defined", function() {
      return expect(User).toBeDefined();
    });
    return it("must have a handler to get current user model", function() {
      return expect(msgbus.reqres.hasHandler('get:current:user:model')).toBe(true);
    });
  });
});
